### ISSUE TITLE
As a developer, I want data models so that I can deal with database

### ISSUE THREAD

**Issue by HarukiMiya** [CS180-spring/cs180-21-chefs-anonymous#19]

**Comment by JayUpadhyayCS** [comment]
https://github.com/orgs/CS180-spring/projects/8/views/4?pane=issue&itemId=26493857

**Comment by JayUpadhyayCS** [comment]
https://github.com/orgs/CS180-spring/projects/8/views/4?pane=issue&itemId=26493526

**Comment by JayUpadhyayCS** [comment]
https://github.com/CS180-spring/cs180-21-chefs-anonymous/issues/27

**Comment by JayUpadhyayCS** [comment]
## Priority: 10
## Story Points: 1
## Test Cases: Visually checking DB, using Postman, outputting to webpage
